baseURL = "https://yaronwittenstein.com"
languageCode = "en-us"
title = "Yaron Wittenstein's Personal Site"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section", "404"]

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/page/about"
[[menu.main]]
    name = "Blog"
    url = "/"
[[menu.main]]
    name = "Newsletter"
    url = "http://read-it-or-throw-it.blogspot.com"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/yaronwittenstein"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/RealWittenstein"

[params]
    mainSections = ["post"]
    description = "Yaron Wittenstein's Personal Site"
