baseURL = "https://yaronwittenstein.netlify.com"
languageCode = "en-us"
title = "Yaron Wittenstein's Personal Site"
theme = "ghostwriter"
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section", "404"]

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

# [[menu.main]]
#     name = "About"
#     url = "/page/about"
[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Newsletter"
    url = "http://read-it-or-throw-it.blogspot.com"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/yaronwittenstein"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/RealWittenstein"
    weight = 4

[params]
    mainSections = ["post", "page"]
    description = "Yaron Wittenstein's Personal Site"
