baseurl = "/"
title = "gryphon.dev"
theme = "hugo-coder"
languagecode = "en-us"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

googleAnalytics = "UA-148359158-1"
disqusShortname = ""

enableGitInfo = true
enableEmoji = true

pygmentsstyle = "friendly"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Yaron Wittenstein"
    info = "A Passionate Coder"
    description = "Yaron Wittenstein's Personal Site"
    keywords="blog,developer,personal"
    avatarurl = "avatar.jpg"

    mainSections = ["posts", "page"]
    favicon = "favicon.ico"
    hidecredits = true
    hidecopyright = true
    rtl = false
    math = true
    inverted = false
    itemscentered = true

    enableTwitterShare = true
    enableLinkedInShare = true

[permalinks]
    posts = "/:year/:month/:day/:title/"
    page = "/:title/"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = false
        disable = false
        respectDoNotTrack = false
        useSessionStorage = false

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/yaronwittenstein"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/RealWittenstein"

[[menu.main]]
    name = "Subscribe"
    url = "/subscribe/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3
[[menu.main]]
    name = "Newsletter"
    url = "https://read-it-or-throw-it.blogspot.com"
    weight = 4
[[menu.main]]
    name = "Talks"
    url = "/talks/"
    weight = 5
