baseURL = "/"
languageCode = "en-us"
title = "Yaron Wittenstein's Personal Site"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-148359158-1"
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section", "404"]

[params]
    author = "Yaron Wittenstein"
    mainSections = ["post", "page"]
    description = "Yaron Wittenstein's Personal Site"
    favicon = "favicon.ico"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"


[[menu.main]]
    name = "About"
    url = "/page/about"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 2
[[menu.main]]
    name = "Newsletter"
    url = "https://read-it-or-throw-it.com"
    weight = 3
[[menu.main]]
    name = "Talks"
    url = "/talks"
    weight = 4
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/yaronwittenstein"
    weight = 5
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/RealWittenstein"
    weight = 6
