baseURL = "https://yaronwittenstein.com"
languageCode = "en-us"
title = "Yaron Wittenstein Site"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""

[[menu.main]]
    name = "About"
    url = "/page/about"
[[menu.main]]
    name = "Talks"
    url = "/page/talks"
[[menu.main]]
    name = "Newsletter"
    url = "http://read-it-or-throw-it.blogspot.com"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/yaronwittenstein"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/RealWittenstein"
